language: php
php:
  - 5.5
  - 7.0
env:
  - SYMFONY="2.6.*"
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
before_install:
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.6.deb && sudo service elasticsearch restart
before_script:
  - composer self-update
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
cache:
  directories:
    - vendor/
    - $HOME/.composer/cache
